# Generated by Django 4.0.2 on 2022-03-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='DrinkImage',
        ),
        migrations.AlterModelTable(
            name='drinkimage',
            table='drink_images',
        ),
    ]
