# Generated by Django 4.0.2 on 2022-03-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(max_length=200),
        ),
    ]
